version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/cmd/preview"
      - "/cmd/shell-extension"
    schedule:
      interval: "weekly"
    groups:
      golang-x:
        patterns:
          - "golang.org/x/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
