# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/icnsify
    id: "icnsify"
    binary: icnsify
    goos:
      - linux
      - windows
      - darwin
archives:
  - format_overrides:
    - goos: windows
      format: zip
brews:
  -
   name: icnsify
   repository:
      owner: "jackmordaunt"
      name: homebrew-tap
scoops:
  -
    repository:
      owner: "jackmordaunt"
      name: scoop-bucket
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
